apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: five31-database
  namespace: five31
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: five31
      owner: app
