apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: five31-database
  namespace: five31
spec:
  instances: 1
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/hetzner-backup: enabled
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: five31
      owner: app
