apiVersion: v1
kind: Service
metadata:
  name: five31-frontend
  namespace: five31
  labels:
    app.kubernetes.io/name: five31-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: five31-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
