apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: five31

resources:
  - frontend.yaml
  - backend.yaml
  - cluster.yaml
  - httproute.yaml
  - securitypolicy.yaml
  - sealedsecret.yaml
  - ciliumnetworkpolicy.yaml
