apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: five31-oidc-client-secret
  namespace: five31
spec:
  encryptedData:
    client-secret: AgAaw3GVK6+Qzqz6CfEmhN9qpNXenpA0zWjaWiU16+lkAIojV3GVbHQKTV1XBPogCN/LzkVAlDr1/igUpO7Y95pcKIp6u7Co1xIAUoLaHgJy2AOCOBf1EAVi7VbZHAGl3qah1+P5PfPpDJ01GREjXE+WDnT5iL13/uOCa6YWmzMBbQD9dbIkrsgqOJ/Lg5BvyG8pTy7bf2bb5ZqqZjR28dzlxuNki9aSBGBX+i8FSqxF+Y54EslgJ/Im7fo3Z1wKE2QTCwwKlu2a2+FOoY6XBQxKgncGnsh/NsIAu9LMo50CVRhXXAf+drcsljcG1uKEccXSpN7193ewLQt36s+xwWTwK6M1fPj4IPwiuS9gnh7MvwMhHzie80U3qWEnssRX1DL/DRKrD7lCxOeg+DvwvQUnQZeTwITiZMa3C02Zhl8LI4aee9sSRQ8FZqrV0S2cnPM2r9j9m53MZimRVyfMQeP0lXhBOVzyZtqg5yVKZwiDJ4BDsYS51qQTqlOZCis6sqa6IrrEpokgH55jRHyKr/rOdLDGb5GXpHrIrPlLlRjDhnC6p3jgwXjzBgduIu5FSip9NOyLTxPpVYhVciSQRxPbj7UNLM0vBkHBdpybIv6AMpyvSRgnd89gNJ/zjMwG4IeJaUBUWOicu75gMWgTw59iprGTHvcISkakBL8pXDkX/aW8Q8+dkcEfdLfGN5hgPFu9TjT6UJSE7lV+SkRwQhJ2ugdFSvW1dHYWCxcM0foQ7iaATZiRh79ydfFLoCb7RadcwPIQEUeAqoX1VpVn61YTKTY083IeWCig0AGvF+kI88TxkfISuMwB19sGwDUd+eGeIZqx5ywHUoh6kkNJ8zi0SXgWGH+Qx5XG6AO1HkwifA==
  template:
    metadata:
      name: five31-oidc-client-secret
      namespace: five31
