name: 'pnpm install'
description: 'Setup pnpm with cache and install dependencies'

inputs:
  node-version:
    required: false
    type: 'string'
    default: '24'
  pnpm-version:
    required: false
    type: 'string'
    default: '10'
  working-directory:
    required: false
    type: 'string'
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4
      name: Install pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: 'false'

    - name: Get pnpm store directory
      id: store-path
      shell: bash
      run: |
        echo "store-path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      name: Setup pnpm cache
      with:
        path: ${{ steps.store-path.outputs.store-path }}
        key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
        restore-keys: '${{ runner.os }}-pnpm-store-'

    - name: Install dependencies
      shell: bash
      run: pnpm i
      working-directory: ${{ inputs.working-directory }}
