name: Cypress end-to-end tests

on:
  pull_request:
    branches: [master]

permissions:
  packages: write
  actions: read

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}/backend'

jobs:
  build-backend:
    name: 'Build backend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache and push to registry
        uses: docker/build-push-action@v6
        with:
          context: 'backend'
          push: 'true'
          tags: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          cache-from: '${{ env.IMAGE_NAME }}:latest'
          cache-to: 'type=inline'

  cypress-e2e-tests:
    name: 'Cypress end-to-end tests'
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start backend
        run: |
          cd backend
          docker compose up &
        env:
          BACKEND_TAG: ${{ github.sha }}

      - name: Setup frontend dependencies
        uses: ./.github/actions/pnpm
        with:
          working-directory: 'frontend'

      - name: Force Cypress install, workaround
        run: |
          cd frontend
          pnpm cypress install

      - name: Run Cypress end-to-end tests
        uses: cypress-io/github-action@v6.7.16
        with:
          working-directory: 'frontend'
          install-command: 'pnpm i'
          build: 'pnpm build'
          start: 'pnpm start'
          wait-on: 'http://localhost:3000, http://localhost:8080/status'
          config: 'video=false'
          browser: 'firefox'
        env:
          NEXTAUTH_SECRET: 'very-secret-string-123'

      - name: Upload Cypress screenshots (only on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: 'cypress-screenshots'
          path: 'frontend/cypress/screenshots'
